### PR TITLE
refactor uai reading

### LINKED ISSUE #49: Removing inplace operations
Now we have `set_evidence!` and `set_query!` to modify a loaded instance in memory.
I think this is not a very good practise because it is hard to track inplace modifications to an object. We should remove `obsvars`, `obsvals` and `queryvars` from the uai instance.

### PR DESCRIPTION
**Pull request by GiggleLiu**
* remove `set_query!` and `set_evidence!`, resolves #49 
* new api: `dataset_from_artifact` to load the whole dataset meta information.
```julia
julia> dataset = dataset_from_artifact("uai2014")
Dict{String, Dict{String, Dict{Int64, ArtifactProblemSpec}}} with 5 entries:
  "MAR"  => Dict("Pedigree"=>Dict(13=>Artifa…
  "MAR2" => Dict("Pedigree"=>Dict(13=>Artifa…
  "MMAP" => Dict("ImageAlignment"=>Dict(13=>…
  "MAP"  => Dict("ImageAlignment"=>Dict(13=>…
  "PR"   => Dict("Segmentation"=>Dict(13=>Ar…

julia> problem = dataset["PR"]["Pedigree"][11]
ArtifactProblemSpec("/home/leo/.julia/artifacts/199ed43697fe22447c6c64a939b222fd4073f2d0", "PR", "Pedigree", 11)

julia> read_instance(problem);

julia> read_evidence(problem)
Dict{Int64, Int64} with 37 entries:
  305 => 2
  52  => 0
  72  => 0
  180 => 1
  17  => 0
  37  => 0
  256 => 1
  ⋮   => ⋮

julia> read_queryvars(problem)
ERROR: SystemError: opening file "/home/leo/.julia/artifacts/199ed43697fe22447c6c64a939b222fd4073f2d0/PR/Pedigree_11.uai.query": No such file or directory
Stacktrace:
...
```

* Changed `TensorNetworkModel` and `MMAPModel` constructors to fit the changes. Variables are more explicitly set.

### CODE REVIEW

**Comment by GiggleLiu** [comment]
@mroavi Please be aware of the upcoming incompatible changes. I have bumped the version to 0.2.

**Review by mroavi — COMMENTED** [review]
I have a few remarks:
1. I noticed that we have functions called `read_xxx_from_file` and others called `read_xxx_file`. Is the naming convention different for some reason? If not, then I propose we make these consistent.
2.    So far we have tried to follow the conventions in https://uaicompetition.github.io/uci-2022/file-formats/. In there, they specify three types of file that are relevant to us: [Model Format](https://uaicompetition.github.io/uci-2022/file-formats/model-format), [Evidence Format](https://uaicompetition.github.io/uci-2022/file-formats/evidence-format), [Query Format (MMAP)](https://uaicompetition.github.io/uci-2022/file-formats/query-format). I noticed that you dropped the name `model` in favor of `instance`. I would keep the name model when referring to the `.uai` file to stay consistent with that website. For me, `instance` is just an object of the `UAIInstance` class.

**Comment by mroavi** [comment]
Today I came up with an idea. Let me know what you think:

We could have a method called `load` (or even extend `read`) that takes one path (AbstractString).
That function would have some logic that calls the proper read function based on the extension of the given path. However, if the path points to a directory instead of a file, then the function tries to read all files (model, evid, and query) in that dir. So if the extension of the given argument is `.uai` then we read the model, if it is `.evid` we read the evidence file, etc. If we receive a path to a directory, then we try to read all three files from that dir and return `nothing` for the files that did not exist in that dir.

This would mean that the user would use `load` (or `read` if you prefer) for everything, which simplifies the user experience. Let me know if you like the idea.

**Comment by mroavi** [comment]
After thinking about this a bit more, it might be better to skip my previous idea for now since we might want to support other file formats in the future, and this decision might make that more difficult.

**Review by mroavi — APPROVED** [review]
All tests pass locally on my machine. Everything looks pretty good to me.

**Pull request merged**
