### PR TITLE
setup documentation

### PR DESCRIPTION
**Pull request by GiggleLiu**
## How to develop
To make life easier, please use the LiveServer,
```bash
julia docs/serve.jl
```

BUT! we need wait for this PR to be merge, otherwise, you will run into infinite loops.
https://github.com/tlienart/LiveServer.jl/pull/168

Examples are included in the `examples` folder, they will be compiled with Literate.
Each folder is an example, each example should contain a `main.jl` file.

### CODE REVIEW

**Comment by GiggleLiu** [comment]
@mroavi Could you please help me fix the tests? the error described here #38

**Comment by mroavi** [comment]
Copy-paste the `Artifacts.toml` inside the `test` dir into the `docs` dir. Let me know if that works.

**Comment by GiggleLiu** [comment]
> @GiggleLiu Copy-paste the `Artifacts.toml` inside the `test` dir into the `docs` dir. Let me know if that works.

I think the question is, is there a convenient way for users to use that artifact.

**Comment by mroavi** [comment]
Yes, there is. They just need to copy paste the `Artifacts.toml` into the root dir of their project, making sure that the artifcat gets installed by adding these lines somewhere at the beginning of the code:

```
  import Pkg;
  Pkg.ensure_artifact_installed("uai2014", joinpath(@__DIR__, "Artifacts.toml"));
```
Now they should be able to get the path to any file in the artifact using the `artifact"<NAME>"` macro, for example:

```julia
      model_filepath = joinpath(artifact"uai2014", "MAR", problem_name * ".uai")
```

The tarball is hosted in a git repo that I created: https://github.com/mroavi/uai-2014-inference-competition.
I plan to move this repo to [TensorBFS](https://github.com/TensorBFS) soon.

**Comment by mroavi** [comment]
The problem that you got above is that the SHA inside the `Artifacts.toml` does not coincide with the SHA of the tarball https://github.com/mroavi/uai-2014-inference-competition/raw/main/uai2014.tar.gz.

**Comment by mroavi** [comment]
I'm almost done fixing the tests (which involves updating the tarball often and following all those steps). As soon as I fix the tests, we are rarely going to need to update the tarball. Let me know if there is stuff that is not clear.

**Comment by GiggleLiu** [comment]
Can we provide a function to help users download the artifacts? otherwise it looks not very friendly in the documentation.

**Comment by mroavi** [comment]
That is what `Pkg.ensure_artifact_installed` does. It is not clear to me how we could make this even simpler. What I did in the docs of `JunctionTrees.jl` was to create an `assets` dir to store the problems used in the examples so that users don't get confused with Artifacts. What do you think of doing something similar in `TensorInference.jl`?

**Comment by GiggleLiu** [comment]
Now I need to tell users in documentation. How to find the Artifacts.toml, where to place the file, how to download it, and how to use it.

I think we can pipeline this workflow. We can still add Artifacts as a dependency, without automatic download. We provide users a function to generate Artifacts.toml and download artifacts. Then another function to import models from it.

**Comment by GiggleLiu** [comment]
The nightly seems to run forever.

**Pull request closed without merging**
